---
- hosts: localhost
  become: true
  tasks:
    - name: Instalar devecot
      dnf:
        name: tree
        state: latest
        
    - name: Subir servicio de apache
      systemd:
        name: httpd
        state: started
...
